#!/bin/bash

NameModes=("M1" "M2" "M4" "M7")
NameTimes=("t50" "t100" "t200" "t400" "t600" "t800" "t1000" "t2000" "t5000" "t10000" "t50000" )
NameAlpha=( "a01" "a02" "a03" "a05" "a1" "a2" "a5" "a10")
NameEps=( "eps001" "eps01" "eps05" "eps1")

Modes=( 1 2 4 7)
T=(50 100 200 400 600 800 1000 2000 5000 10000 50000)
A=(0.1 0.2 0.3 0.5 1.0 2.0 5.0 10.0)
eps=(0.01 0.1 0.5 1.0)

#clean and recreate the directories with the data sets
for l in {0..3}
do
    rm -r "${NameEps[l]}"
    mkdir "${NameEps[l]}"
done

#create the data sets
for i in {0..1}
do
    for j in {5..5}
    do
	for k in {0..7}
	do
	    for l in {0..3}
	    do
		
	   
		echo "i= $i, j=$j, k=$k, l=$l \n"
		rm pass.txt
		
		touch pass.txt
		echo -e "10 \n${A[k]} \n0.01 \n${T[j]} \nt \n${Modes[i]} \n${eps[l]}"  >> pass.txt  
		./a.out < pass.txt
	    	
		mv modes_t.dat "./${NameEps[l]}/modes_${NameModes[i]}_${NameTimes[j]}_${NameAlpha[k]}.dat"
		mv power_spectrum.dat "./${NameEps[l]}/ps_${NameModes[i]}_${NameTimes[j]}_${NameAlpha[k]}.dat"
		mv avg_modes.dat "./${NameEps[l]}/avgmodes_${NameModes[i]}_${NameTimes[j]}_${NameAlpha[k]}.dat"
		rm pass.txt
		
	    done
	done
    done
done
